# Generated by Django 5.2.6 on 2025-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_in', models.IntegerField()),
                ('money_out', models.IntegerField()),
                ('current_balance', models.IntegerField()),
                ('category', models.CharField()),
                ('tag', models.CharField(choices=[('--', '--'), ('WANTS', 'WANTS'), ('NEEDS', 'NEEDS'), ('SAVINGS', 'SAVINGS')], default='--')),
                ('payee', models.CharField()),
                ('transaction_date', models.DateField()),
                ('account', models.CharField()),
                ('description', models.CharField()),
                ('cleared', models.BooleanField()),
            ],
        ),
    ]
