# Generated by Django 5.2.6 on 2025-10-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_in', models.IntegerField()),
                ('money_out', models.IntegerField()),
                ('current_balance', models.IntegerField()),
                ('category', models.CharField()),
                ('tag', models.CharField(choices=[('--', '--'), ('INCOME', 'INCOME'), ('WANTS', 'WANTS'), ('NEEDS', 'NEEDS'), ('SAVINGS', 'SAVINGS')], default='--')),
                ('payee', models.CharField()),
                ('transaction_date', models.DateField()),
                ('account', models.CharField()),
                ('description', models.CharField()),
                ('cleared', models.BooleanField()),
                ('timeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.timeline')),
            ],
        ),
    ]
