# Generated by Django 5.2.6 on 2025-09-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.CharField(choices=[('--', '--'), ('INCOME', 'INCOME'), ('WANTS', 'WANTS'), ('NEEDS', 'NEEDS'), ('SAVINGS', 'SAVINGS')], default='--'),
        ),
    ]
