# Generated by Django 5.2.7 on 2025-10-09 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwithbrandon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='timeline_name',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timeline',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='budgetwithbrandon.timeline'),
        ),
    ]
