# Generated by Django 5.2.7 on 2025-10-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwithbrandon', '0002_alter_timeline_timeline_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='timeline',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
